# Generated by Django 5.2.12 on 2026-04-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_gallery", "Can view the design system gallery")
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
